import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function exportDashboardPdf({
  workspaceName,
  selectedRange,
  user,
  stats,
  trendData,
  trendFormat,
  activities,
  recentProjects,
  myTasks,
  dueSoonTasks,
}) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  // Helper to draw footer on each page
  const drawFooter = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(150);
      const timestamp = new Date().toLocaleString();
      doc.text(
        `Generated by TaskFlow Pro  •  Page ${i} of ${pageCount}  •  ${timestamp}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );
    }
  };

  // --- 1. Header Section ---
  // Top purple accent bar
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 0, pageWidth, 4, "F");

  // Logo / Title area
  doc.setFontSize(24);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("TaskFlow Pro", margin, 22);

  doc.setFontSize(14);
  doc.setTextColor(99, 102, 241); // indigo-500
  doc.setFont("helvetica", "normal");
  doc.text("Dashboard Report", margin, 30);

  // Meta info box
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, 38, contentWidth, 24, 2, 2, "FD");

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105); // slate-600
  
  // Left meta
  doc.setFont("helvetica", "bold");
  doc.text("Workspace:", margin + 5, 46);
  doc.text("Date Range:", margin + 5, 54);
  
  doc.setFont("helvetica", "normal");
  doc.text(workspaceName || "Unknown Workspace", margin + 35, 46);
  doc.text(selectedRange || "Unknown Range", margin + 35, 54);

  // Right meta
  doc.setFont("helvetica", "bold");
  doc.text("Generated by:", pageWidth / 2 + 5, 46);
  doc.text("Generated on:", pageWidth / 2 + 5, 54);

  doc.setFont("helvetica", "normal");
  doc.text(`${user?.name || "Unknown"} (${user?.email || "No email"})`, pageWidth / 2 + 35, 46);
  doc.text(new Date().toLocaleDateString(), pageWidth / 2 + 35, 54);

  let startY = 75;

  // Helper to check page break
  const checkPageBreak = (neededHeight) => {
    if (startY + neededHeight > pageHeight - 20) {
      doc.addPage();
      startY = margin + 10;
    }
  };

  // --- 2. Summary Metrics (Cards) ---
  checkPageBreak(50);
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("Summary Metrics", margin, startY);
  startY += 8;

  const totalProjects = stats?.projects?.total || 0;
  const activeTasks = Math.max((stats?.tasks?.total || 0) - (stats?.tasks?.done || 0), 0);
  const completedTasks = stats?.tasks?.done || 0;
  const overdueTasks = stats?.tasks?.overdue || 0;

  const cardWidth = (contentWidth - 6) / 2; // 2x2 grid, 6mm gap
  const cardHeight = 22;

  const drawCard = (x, y, title, value, accentColor) => {
    // Card background
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, "FD");

    // Accent left border
    doc.setFillColor(...accentColor);
    // Draw a small rect over the left edge to simulate left border accent
    doc.roundedRect(x, y, 3, cardHeight, 2, 2, "F");
    // Cover right side of the accent rect to make it flat on right
    doc.rect(x + 1.5, y, 1.5, cardHeight, "F");

    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(title, x + 8, y + 8);

    doc.setFontSize(18);
    doc.setTextColor(30);
    doc.setFont("helvetica", "bold");
    doc.text(value.toString(), x + 8, y + 17);
  };

  drawCard(margin, startY, "Total Projects", totalProjects, [139, 92, 246]); // violet-500
  drawCard(margin + cardWidth + 6, startY, "Active Tasks", activeTasks, [59, 130, 246]); // blue-500
  drawCard(margin, startY + cardHeight + 6, "Completed Tasks", completedTasks, [16, 185, 129]); // emerald-500
  drawCard(margin + cardWidth + 6, startY + cardHeight + 6, "Overdue Tasks", overdueTasks, [239, 68, 68]); // red-500

  startY += (cardHeight * 2) + 16;

  // --- 3. Task Volume Trend Section ---
  checkPageBreak(50);
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("Task Volume Trend", margin, startY);
  startY += 6;

  // Mini stats for trend
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  const trendSubtext = `Selected Range: ${selectedRange}  |  Created: ${stats?.tasks?.newLast30 || 0}  |  Completed: ${stats?.tasks?.completedLast30 || 0}  |  In Progress: ${stats?.tasks?.inProgress || 0}`;
  doc.text(trendSubtext, margin, startY);
  startY += 6;

  if (trendData && trendData.length > 0) {
    let trendHead = ["Date", "New Tasks Count"];
    if (trendFormat === 'status') trendHead = ["Status", "Task Count"];
    else if (trendFormat === 'weekly') trendHead = ["Week", "New Tasks Count"];
    else if (trendFormat === 'monthly') trendHead = ["Month", "New Tasks Count"];

    const trendRows = trendData.map((t) => {
      let label = t._id;
      if (trendFormat === 'status') {
          const statusMap = {
              "todo": "To Do",
              "in_progress": "In Progress",
              "review": "Review",
              "done": "Done",
              "blocked": "Blocked"
          };
          label = statusMap[t._id] || t._id;
      } else if (trendFormat === 'daily') {
          label = new Date(t._id).toLocaleDateString();
      } else if (trendFormat === 'weekly') {
          const parts = t._id.split('-');
          label = `Week ${parts[1]}, ${parts[0]}`;
      } else if (trendFormat === 'monthly') {
          const date = new Date(`${t._id}-01T00:00:00Z`);
          label = date.toLocaleString('default', { month: 'long', year: 'numeric' });
      }
      return [label, t.count];
    });

    autoTable(doc, {
      startY: startY,
      head: [trendHead],
      body: trendRows,
      theme: "plain",
      headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' }, // slate-100
      bodyStyles: { textColor: [30, 41, 59] },
      alternateRowStyles: { fillColor: [248, 250, 252] }, // slate-50
      styles: { fontSize: 10, cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.1 },
      margin: { left: margin, right: margin },
      tableWidth: 'auto',
    });
    startY = doc.lastAutoTable.finalY + 15;
  } else {
    // Empty state
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, startY, contentWidth, 15, 2, 2, "FD");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("No task trend data available for this period.", margin + 5, startY + 10);
    startY += 25;
  }

  // --- 4. My Tasks Section ---
  if (myTasks && myTasks.length > 0) {
    checkPageBreak(50);
    doc.setFontSize(16);
    doc.setTextColor(30);
    doc.setFont("helvetica", "bold");
    doc.text("My Tasks", margin, startY);
    startY += 6;

    const myTaskRows = myTasks.map(t => [
      t.title || "Untitled",
      t.project?.name || "N/A",
      t.status?.replace("_", " ") || "todo",
      t.priority || "medium",
      t.dueDate ? new Date(t.dueDate).toLocaleDateString() : "—"
    ]);

    autoTable(doc, {
      startY: startY,
      head: [["Title", "Project", "Status", "Priority", "Due Date"]],
      body: myTaskRows,
      theme: "plain",
      headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
      bodyStyles: { textColor: [30, 41, 59] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 10, cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.1 },
    });
    startY = doc.lastAutoTable.finalY + 15;
  }

  // --- 5. Due Soon Section ---
  if (dueSoonTasks && dueSoonTasks.length > 0) {
    checkPageBreak(50);
    doc.setFontSize(16);
    doc.setTextColor(30);
    doc.setFont("helvetica", "bold");
    doc.text("Due Soon Tasks", margin, startY);
    startY += 6;

    const dueSoonRows = dueSoonTasks.map(t => [
      t.title || "Untitled",
      t.project?.name || "N/A",
      t.assignee?.name || "Unassigned",
      t.status?.replace("_", " ") || "todo",
      t.dueDate ? new Date(t.dueDate).toLocaleDateString() : "—"
    ]);

    autoTable(doc, {
      startY: startY,
      head: [["Title", "Project", "Assignee", "Status", "Due Date"]],
      body: dueSoonRows,
      theme: "plain",
      headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
      bodyStyles: { textColor: [30, 41, 59] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 10, cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.1 },
    });
    startY = doc.lastAutoTable.finalY + 15;
  }

  // --- 6. Recent Projects Section ---
  checkPageBreak(50);
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("Recent Projects", margin, startY);
  startY += 6;

  if (!recentProjects || recentProjects.length === 0) {
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, startY, contentWidth, 15, 2, 2, "FD");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text("No recent projects found.", margin + 5, startY + 10);
    startY += 25;
  } else {
    const projectRows = recentProjects.map((p) => {
      const createdDate = p.createdAt ? new Date(p.createdAt).toLocaleDateString() : "—";
      return [
        p.name || "Untitled",
        p.client?.name || "N/A",
        p.status || "active",
        p.priority || "medium",
        createdDate,
      ];
    });

    autoTable(doc, {
      startY: startY,
      head: [["Project Name", "Client", "Status", "Priority", "Created Date"]],
      body: projectRows,
      theme: "plain",
      headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
      bodyStyles: { textColor: [30, 41, 59] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 9, cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.1, overflow: 'linebreak' },
      margin: { left: margin, right: margin },
      didParseCell: function (data) {
        if (data.section === 'body') {
          if (data.column.index === 2) { // Status
            const status = data.cell.raw.toString().toLowerCase();
            if (status === 'completed' || status === 'done') data.cell.styles.textColor = [16, 185, 129];
            else if (status === 'active' || status === 'in_progress') data.cell.styles.textColor = [59, 130, 246];
            else if (status === 'on_hold' || status === 'blocked') data.cell.styles.textColor = [239, 68, 68];
          }
          if (data.column.index === 3) { // Priority
            const prio = data.cell.raw.toString().toLowerCase();
            if (prio === 'high' || prio === 'urgent') data.cell.styles.textColor = [239, 68, 68];
            else if (prio === 'medium') data.cell.styles.textColor = [245, 158, 11];
            else if (prio === 'low') data.cell.styles.textColor = [100, 116, 139];
          }
        }
      }
    });
    startY = doc.lastAutoTable.finalY + 15;
  }

  // --- 7. Recent Activity Section ---
  checkPageBreak(50);
  doc.setFontSize(16);
  doc.setTextColor(30);
  doc.setFont("helvetica", "bold");
  doc.text("Recent Activity", margin, startY);
  startY += 6;

  if (!activities || activities.length === 0) {
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, startY, contentWidth, 15, 2, 2, "FD");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text("No activity found for this period.", margin + 5, startY + 10);
  } else {
    const activityRows = activities.slice(0, 30).map((act) => {
      // Clean up the type badge text
      let actType = act.id ? act.id.split('_')[0].toUpperCase() : "ACTIVITY";
      // Format time safely
      let actTime = "—";
      if (act.time) {
        // If it's a relative string like "2 hours ago", keep it. Otherwise try to format it.
        actTime = act.time; 
      }
      return [
        actType,
        act.title || "Unknown",
        act.desc || "",
        actTime,
      ];
    });

    autoTable(doc, {
      startY: startY,
      head: [["Type", "Title", "Description", "Time"]],
      body: activityRows,
      theme: "plain",
      headStyles: { fillColor: [241, 245, 249], textColor: [71, 85, 105], fontStyle: 'bold' },
      bodyStyles: { textColor: [30, 41, 59], valign: 'top' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 9, cellPadding: 4, lineColor: [226, 232, 240], lineWidth: 0.1, overflow: 'linebreak' },
      margin: { left: margin, right: margin },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: [99, 102, 241] }, // Type
        1: { fontStyle: 'bold' }, // Title
        2: { }, // Description (auto wrapped)
        3: { textColor: [100, 116, 139] }, // Time
      },
    });
  }

  // --- Add footer to all pages ---
  drawFooter();

  // Create formatted filename
  const cleanWorkspace = workspaceName
    ? workspaceName.toLowerCase().replace(/[^a-z0-9]+/g, "-")
    : "workspace";
  const cleanRange = selectedRange.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const dateStr = new Date().toISOString().split("T")[0];
  const filename = `taskflow-dashboard-report-${cleanWorkspace}-${cleanRange}-${dateStr}.pdf`;

  // Save the PDF
  doc.save(filename);
}
